### ISSUE TITLE
Message:  array_merge(): Argument #2 is not an array

### ISSUE THREAD

**Issue by bichitra12** [atishhamte/rest-server-codeigniter-2.2.x#1]
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>

<p>Message:  array_merge(): Argument #2 is not an array</p>

<p>Filename: libraries/Rest.php</p>

<p>Line Number: 528</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>

<p>Message:  array_merge(): Argument #1 is not an array</p>

<p>Filename: libraries/Rest.php</p>

<p>Line Number: 327</p>

</div>{"status":false,"error":false}

**Comment by AdityaCompaddicts** [comment]
Same issue

**Comment by jcruzmontanari** [comment]
Hello, I fixed with this
Line #538 
Replace this:
 $this->_get_args = array_merge($this->_get_args, $this->_query_args);

With this:
 $this->_get_args = array_merge($this->_get_args, ($this->_query_args) ? $this->_query_args : array());

**Comment by productivitycave** [comment]
Hi,

What about post method case?
I could see the same error using curl command like below.

curl -X POST https://hogehoge


--
A PHP Error was encountered

Severity: Warning
Message:  array_merge(): Argument #3 is not an array
Filename: libraries/Rest.php
Line Number: 330
